[project]
name = "py-snmp-sync"
version = "1.0.1"
description = "Lightweight synchronous SNMPv1 Client implemented as a PySNMP wrapper optimized for sequential queries"
readme = "README.md"
requires-python = ">=3.7"
license = "EUPL-1.2"
authors = [
  {name = "Ircama"}
]
dependencies = [
  "pysnmp>=7.0.0"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = "https://github.com/Ircama/py-snmp-sync"

[tool.setuptools]
packages = ["py_snmp_sync"]
