[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ytdx"
version = "0.1.1"
description = "Загрузчик видео с YouTube через командную строку"
authors = [
    {name = "Flaymie", email = "funquenop@gmail.com"}
]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.6"
dependencies = [
    "yt-dlp",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Flaymie/ytdx"

[project.scripts]
ytdx = "ytdx:main"

[tool.setuptools]
py-modules = ["ytdx"] 