[project]
name = "miniroute"
version = "0.2.3"
description = "A minimal HTTP routing framework based on Python’s built-in `http.server` for IPC tooling."
license = "PSF"
authors = [
    {name = "Léo Hehlen",email = "leo.hehlen@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
]

[tool.poetry]
packages = [{include = "miniroute", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
