[tool.poetry]
name = "ambientagi"
version = "0.2.1"
description = "Your all-in-one SDK to automate multi-agent tasks"
authors = ["ambientagi admin@ambientagi.com"]
readme = "README.md"
packages = [{ include = "ambientagi" }]

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
requests = ">=2.32.3,<3.0.0"
pydantic-settings = ">=2.7.1,<3.0.0"
boto3 = "^1.28.0"
playwright = "^1.49.1"
pydantic = "^2.0"
APScheduler =">=3.11.0"
firecrawl-py =">=1.10.2"
requests-oauthlib = "^2.0.0"
browser-use = "0.1.29"
pyperclip = "1.9.0"
gradio = "5.10.0"
json-repair = "*"
langchain-mistralai = "0.2.4"
reportlab = "4.3.1"
Markdown = "3.7"
openai="1.66.3"
openai-agents="0.0.4"
python-logging-loki="0.3.1"
python-dotenv="1.0.1"
eth-account = { version = "0.13.7", extras = ["secure"] }

[tool.poetry.group.dev.dependencies]
pytest = "^7.0"
pytest-asyncio = "^0.20.3"
moto = "^4.1.10"

[tool.poetry.scripts]
ambientagi-webui = "ambientagi.webui.webui:main"
post_install_playwright = "ambientagi.utils.playwright_installer:run"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
ignore_missing_imports = true

[tool.mypy."requests.*"]
ignore_missing_imports = true

[tool.isort]
profile = "black"
