# pyproject.toml

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ripple_down_rules"
version = "0.4.3"
description = "Implements the various versions of Ripple Down Rules (RDR) for knowledge representation and reasoning."
readme = "README.md"
authors = [{ name = "Abdelrhman Bassiouny", email = "abassiou@uni-bremen.de" }]
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3",
]
keywords = ["robotics", "knowledge", "reasoning", "representation"]
dependencies = []
requires-python = ">=3.10"

[project.urls]
Homepage = "https://github.com/AbdelrhmanBassiouny/ripple_down_rules"
