[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "cmake>=3.15",          # <- crucial
    "pybind11[global]>=2.6" # <- if you're using pybind11
]
build-backend = "setuptools.build_meta"

