[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = 'pygmi'
dynamic = ['version']
authors = [{name = 'Patrick Cole', email = 'pcole@geoscience.org.za'}]
maintainers = [{name = 'Patrick Cole', email = 'pcole@geoscience.org.za'}]
description = 'Python Geoscience Modelling and Interpretation'
readme = 'README.rst'
requires-python = '>=3.10'
license = "GPL-3.0-or-later"
license-files = ["LICENSE.txt"]
keywords=['Geoscience', 'Geophysics', 'Magnetic', 'Gravity', 'Modelling',
          'Interpretation', 'Remote Sensing']
classifiers = [
    'Development Status :: 5 - Production/Stable',
    'Environment :: Win32 (MS Windows)',
    'Environment :: X11 Applications :: Qt',
    'Intended Audience :: Education',
    'Intended Audience :: End Users/Desktop',
    'Intended Audience :: Science/Research',
    'Natural Language :: English',
    'Operating System :: Microsoft :: Windows',
    'Operating System :: POSIX :: Linux',
    'Programming Language :: Python :: 3',
    'Topic :: Scientific/Engineering :: Mathematics',
    'Topic :: Scientific/Engineering :: Physics',
    'Topic :: Scientific/Engineering :: Image Processing',
    'Topic :: Scientific/Engineering :: Visualization',
    'Topic :: Software Development :: Libraries :: Python Modules',
]

dependencies = [
                'fiona>=1.10.1',
                'geopandas>=1.0.1',
                'h5netcdf>=1.6.1',
                'matplotlib>=3.10.1',
                'mtpy>=1.1.5',
                'natsort>=8.4.0',
                'numba>=0.61.2',
                'numexpr>=2.10.2',
                'openpyxl>=3.1.5',
                'psutil>=7.0.0',
                'pyside6>=6.9.0',
                'pytest>=8.3.5',
                'pyvista>=0.45.0',
                'pyvistaqt>=0.11.2',
                'rasterio>=1.4.3',
                'rioxarray>=0.19.0',
                'scikit-learn>=1.6.1',
                'scikit-image>=0.25.2',
                'shapelysmooth>=0.2.1',
                'simpeg>=0.24.0',
                'beautifulsoup4>=4.13.4',
                ]

[project.urls]
homepage = 'http://patrick-cole.github.io/pygmi/'
documentation = 'https://patrick-cole.github.io/pygmi/wiki.html'
repository =  'https://github.com/Patrick-Cole/pygmi.git'
changelog = 'https://github.com/Patrick-Cole/pygmi/blob/pygmi3/CHANGES.rst'

[project.scripts]
pygmi-cli = 'pygmi.main:main'

[project.gui-scripts]
pygmi-gui = 'pygmi.main:main'
pygmi = 'pygmi.main:main'

[tool.setuptools.package-dir]
pygmi = 'pygmi'

[tool.setuptools.dynamic]
version = {attr = 'pygmi.version.__version__'}