[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pripy-utils"
version = "0.1.1"
keywords = ["utils", "mylog", "zip", "sqlite3", "database"]
description = "个人python工具集"
readme = "README.md"
requires-python = ">=3.13"
license = "MIT AND (Apache-2.0 OR BSD-2-Clause)"
authors = [
  {name = "JAYSENLIN", email = "jaysen.lin@foxmail.com"}
]
dependencies = [
  "requests>=2.31.0",  # 依赖示例
  
]

[project.urls]
Homepage = "https://home.codelin.vip"
Documentation = "https://deepseeksblog.web.app/"
Repository = "https://github.com/linjonh/pripy-utils"
"Official Website" = "https://codelin.vip"