[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "collinear"
version = "0.1.33"
authors = [
    { name = "Asad", email = "asad@collinear.ai" },
]
description = "Python Client SDK for Collinear AI"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "setuptools~=75.1.0",
    "pydantic~=2.9.2",
    "requests~=2.32.3",
    "aiohttp~=3.10.10",
    "pandas~=2.2.3",
    "openai~=1.52.0",
    "tqdm~=4.66.5",
    "asynciolimiter",
    "anthropic",
    "tenacity",
    "jinja2",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
license = { text = "MIT" }

[project.urls]
Homepage = "https://www.collinear.ai/"