[project]
name = "lzhasynctcpclient"
version = "0.1.6"
description = "An asyncio-based threaded TCP client with heartbeat and auto-reconnect"
readme = "README.md"
license = { text = "MIT" }
authors = [
  { name="lzh", email="zhhtdm@hotmail.com" }
]
dependencies = [
    "lzhgetlogger"
]
keywords = ["tcp", "asyncio", "client", "network", "reconnect"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.7"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
