# pyproject.toml

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ripple_down_rules"
version = "0.4.81"
description = "Implements the various versions of Ripple Down Rules (RDR) for knowledge representation and reasoning."
readme = "README.md"
authors = [{ name = "Abdelrhman Bassiouny", email = "abassiou@uni-bremen.de" }]
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3",
]
keywords = ["robotics", "knowledge", "reasoning", "representation"]
dependencies = [
    "anytree>=2.8.0",
    "pandas>=2.0.3",
    "networkx>=3.1",
    "ordered_set>=4",
    "pygraphviz>=1.7",
    "ucimlrepo>=0.0.7",
    "typing-extensions>=4.12.2",
    "matplotlib>=3.7.5",
    "sqlalchemy",
    "pyqt6",
    "qtconsole",
    "graphviz",
    "tabulate",
    "ipython",
    "requests",
    "colorama",
]
