[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pdf-section-sentiment"  # pip install name
version = "0.1.4"
description = "Extract sections from PDFs and perform sentiment analysis"
readme = {file = "README.md", content-type = "text/markdown"}
license = {file = "LICENSE"}

authors = [
  { name="Sanjay BK", email="krishsan1963@gmail.com" }
]

dependencies = [
  "docling",
  "markdown",
  "textblob",
  "pandas",
  "langchain-text-splitters"
]

[project.urls]
Homepage = "https://github.com/sanjaybk7/pdf-section-sentiment"

[project.scripts]
pdf-extract = "pdf_section_sentiment.extract_pdf:main"
pdf-sentiment = "pdf_section_sentiment.sentiment:main"
