

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "anbima-data"  # Nome simples e tudo minÃºsculo
version = "0.1.0"
description = "Provides Python functions to retrieve public data from ANBIMA related to the Brazilian fixed income market."
authors = [
  { name="Aliane Vieira de Castro", email="seu@email.com" }
]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.7"
dependencies = [
  "pandas",
  "requests",
  "plotly",
  "beautifulsoup4",
]

[project.urls]
"Homepage" = "https://github.com/AlianeVdeC/anbima-data"
