[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "rhoshift"
version = "0.1.3.5"
description = "RHOAI tool kit for managing and upgrading RHOAI"
requires-python = ">=3.8"
dependencies = [
    "pytest",
    "openshift-client",
    "boto3", 
    "python-dotenv",
    "requests",
    "kubernetes",
]
[tool.hatch.build.targets.wheel]
packages = ["rhoshift"]

[project.scripts]
rhoshift = "main:main"
#run-upgrade-matrix = "rhoai_upgrade_matrix.cli:run_upgrade_matrix"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "--verbose"

[tool.ruff]
line-length = 100
target-version = "py38" 