[project]
name = "hungovercoders_repo_tools"
version = "0.1.93"
description = "hungovercoders repository tools for managing and monitoring quality of repositories."
readme = "README.md"
authors = [
    { name = "dataGriff", email = "info@hungovercoders.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
hungovercoders-todo = "hungovercoders_repo_tools.todo:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
