[project]
name = "wordle-cli"
version = "0.2.0"
description = "Wordle game for your terminal"
readme = "README.md"
authors = [
    { name = "gautam" }
]
requires-python = ">=3.9"
dependencies = ["pyfiglet"]

[project.scripts]
wordle = "wordle.game:main"

[tool.setuptools]
packages = ["wordle"]

[tool.setuptools.package-data]
wordle = ["words.txt", "valid.txt"]

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"