[project]
name = "typeric"
version = "0.1.1"
description = "**typeric** is a practical type utility toolkit for Python, focused on clarity, safety, and ergonomics"
readme = "README.md"
authors = [
    { name = "dfine", email = "coding@dfine.tech" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
typeric = "typeric:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]

[tool.setuptools.package-data]
"typeric" = ["py.typed"]
