[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lyzr-mcp-tool-call"
version = "0.1.5"
description = "An MCP server for calling Lyzr agents"
readme = "README.md"
authors = [
    {name = "Rasswanth", email = "rasswanth@lyzr.ai"}
]
requires-python = ">=3.10"
dependencies = [
    "fastmcp>=2.4.0",
    "twine>=6.1.0",
]

[project.scripts]
lyzr-mcp-tool-call = "lyzr_tool_call.server:main"

[tool.setuptools]
package-dir = {"" = "src"}
