[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "envypy"
version = "0.0.5"
authors = [
  { name="Zachary Jones", email="zacharyj@orbical.dev" },
]
description = "Envybase python sdk"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/orbical-dev/envybase"
Issues = "https://github.com/pypa/orbical-dev/envybase/issues"