[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Damen_profiling_tools"
version = "0.0.3"
description = "Damen-library"
license =  {text = "MIT"}
authors = [
    { name="giandaeky", email="giandaekyoga10@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.8"

[project.urls]
Homepage = "https://pypi.org/project/damen-profiling/"

[tool.setuptools.packages.find]
where = ["."]