[tool.isort]
profile = "black"

[tool.poetry]
name = "parsomics-cli"
version = "2.3.0"
description = "A command line interface (CLI) for parsomics."
authors = ["Pedro Sader Azevedo <pedro.saderazevedo@lnbr.cnpem.br>"]
license = "GPL-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
typer = "^0.15.1"
podman = "^5.2.0"
keyring = "^25.6.0"
sqlmodel = "^0.0.22"
gitpython = "^3.1.44"
psutil = "^6.1.1"
parsomics-core = "^3.0.1"

[tool.poetry.group.dev.dependencies]
isort = "^5.13.2"
black = "^24.10.0"

[tool.poetry.scripts]
parsomics = "parsomics_cli.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
