[tool.poetry]
authors = ["Alex Basile <basileaw@gmail.com>"]
description = "Serve Python CLI applications in the browser using ttyd"
license = "MIT"
name = "terminaide"
packages = [
  {include = "terminaide"},
  {include = "terminarcade"},
]
readme = "README.md"
repository = "https://github.com/bazeindustries/terminaide"
version = "0.6.1"

[tool.poetry.dependencies]
bs4 = "^0.0.2"
h11 = "^0.16.0"
httpcore = "^1.0.9"
httpx = "^0.28.1"
jinja2 = "^3.1.2"
pydantic = "^2.4.2"
python = ">=3.12"
readchar = "^4.2.1"
rich = "^14.0.0"
websockets = "^12.0"
fastapi = "^0.115.12"
uvicorn = "^0.34.2"
pywebview = "^5.4"
requests = "^2.32.3"

[tool.poetry.group.demo.dependencies]
docker = "^7.1.0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
