[build-system]
requires = ["flit_core>=3.4,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "dtools.iterables"
version = "2.0.0"
authors = [{ name = "Geoffrey R. Scheller", email = "geoffrey@scheller.com" }]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Framework :: Pytest",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.13",
    "Typing :: Typed",
]
dynamic = ["description"]
keywords = [
    "iterables",
    "iterators",
]
dependencies = [
    "dtools.circular-array>=3.15.0, <3.16",
    "dtools.containers >=1.0.0, <1.1",
    "dtools.fp >=2.0.0, <2.1",
]

[project.optional-dependencies]
test = [
    "pytest >=8.3.5",
]

[project.urls]
Homepage = "https://github.com/grscheller/dtools-namespace-projects/blob/main/README.md"
Source = "https://github.com/grscheller/dtools-iterables"
Changelog = "https://github.com/grscheller/dtools-iterables/blob/main/CHANGELOG.md"
Documentation = "https://grscheller.github.io/dtools-namespace-projects/iterables"

[tool.flit.sdist]
exclude = ["dist", "tests", ".gitignore", ".mypy_cache", ".pytest_cache"]

[tool.pytest.ini_options]
consider_namespace_packages = true

[tool.pylsp-mypy]
enabled = true
live-mode = true
strict = true
report_progress = true

[tool.mypy]
enable_incomplete_feature = ["NewGenericSyntax"]
implicit_reexport = false
local_partial_types = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_configs = true

[tool.ruff]
target-version = "py313"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"

[tool.ruff.format]
quote-style = "single"
docstring-code-line-length = 72
