#[build-system]
#requires = ["setuptools>=61", "wheel"]
#build-backend = "setuptools.build_meta"
#
#[project]
#name = "ip-discovery"
#version = "1.1.1"
#description = "ip-discovery is an open-source Python library designed to enhance automation workflows across a wide range of operating systems, including RHEL, SLES, Ubuntu, VMware, Windows, Oracle, and more.By enabling fully automated post-deployment IP discovery."
#authors = [
#    { name = "Vikas Kumar", email = "fusionvikas.py@gmail.com" }
#]
#readme = "README.md"
#license = "MIT"
#requires-python = ">=3.7"
#dependencies = []
#dynamic = ["classifiers"]
#
#
#[project.urls]
#Homepage = "https://github.com/fusionvikas2015/ipDiscovery.git"


[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ipDiscovery"
version = "1.1.2"
description = "ip-discovery is an open-source Python library to enhance automation workflows for IP discovery."
authors = [
    { name = "Vikas Kumar", email = "fusionvikas.py@gmail.com" }
]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.7"
dependencies = [
    "cryptography",
    "paramiko"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]
dynamic = []

[project.urls]
Homepage = "https://github.com/fusionvikas2015/ipDiscovery"
