[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mia-amis"
version = "0.1.0.1"
description = "Assistant Module Interface System"
authors = [
    {name = "RayzorST"},
]
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
]

dependencies = [
    "watchdog>=2.0.0", "keyboard>=0.13.5"
]

[project.optional-dependencies]
dev = [
    "pytest>=6.0",
    "black>=21.0",
    "mypy>=0.900",
    "flake8>=3.9",
]

[project.urls]
Homepage = "https://github.com/RayzorST/Assistant-Module-Interface-System"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-dir]
amis = "amis"

[tool.setuptools.packages.find]
where = ["."]  # Искать в корне
include = ["amis*"]

[tool.black]
line-length = 120
target-version = ['py38']