[project]
name = "pyumls_similarity"
version = "0.1.5"
authors = [
  { name="Victor Murcia", email="victor.murcia@wsu.edu" },
]
description = "A semantic reasoning and graph analysis engine for biomedical concepts using the UMLS."
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
    "Topic :: Software Development :: Libraries :: Python Modules"
]
keywords = ["nlp", "ontology", "umls", "medicine", "networks"]
license = "MIT"

[project.urls]
Homepage = "https://github.com/victormurcia/PyUMLS_Similarity2"
Issues = "https://github.com/victormurcia/PyUMLS_Similarity2/issues"
Repository = "https://github.com/victormurcia/PyUMLS_Similarity2.git"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
