[tool.poetry]
name = "versein"                     # Must be unique on PyPI
version = "0.1.3"
description = "Minimal Python SDK with Greeter class"
authors = ["Muhammad Azeem <you@example.com>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "versein", from = "src" }]

[tool.poetry.dependencies]
python = "^3.10"
