[build-system]
requires      = ["setuptools==61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dxt"
version = "0.0.1"
authors = [
    {name = "4sushi"},
]
description = "dxt"
readme = "README.md"
requires-python = ">=3.7"
keywords = ["dxt"]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = []


