[project]
name = "LynqX"
version = "1.0.6"
description = "A Textual-based terminal chat client offering real-time messaging, file sharing, typing indicators, and emoji support."
readme = "README.md"
requires-python = ">=3.12"
license = { text = "MIT" }
authors = [
    { name = "MD. Shahariar Ahmmed Shovon" },
    { email = "shovonali885@gmail.com" }
]

dependencies = [
    "textual",
    "httpx",
    "requests",
    "sseclient",
    "emoji",
    "websockets"
]

[project.urls]
Homepage = "https://github.com/SwagCoder18/LynqX"

[project.scripts]
lynqx = "LynqX.app:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
