[project]
name = "tesseral-flask"
version = "0.0.5"
description = "Tesseral SDK for Flask"
readme = "README.md"
authors = [
    { name = "Ulysse Carion", email = "ulysse.carion@tesseral.com" },
    { name = "Blake Williams", email = "blake.williams@tesseral.com" }
]
requires-python = ">=3.9"
dependencies = [
    "flask>=2.0.0",
    "httpx>=0.28.1",
    "tesseral-sdk>=0.0.10",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "python-dotenv>=1.1.0",
    "ruff>=0.11.3",
]
