[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "letter-art"
version = "0.1.4"
description = "Convert images into ASCII art in Python"
readme = "README.md"
requires-python = ">=3.7"
authors = [{name = "gwondoo", email = "kdh30166568@gmail.com"}]
license = {text = "MIT"}

dependencies = ["pillow"]

[project.urls]
"Homepage" = "https://github.com/gwondoo/letter_art"
