[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ragformance"
version = "0.1.79"
description = "A library for generating dataset and evaluating these datasets on RAG based solutions"
readme = "README.md"
requires-python = ">=3.9,<3.13"
authors = [
    { name="FOR Team", email="jonathan.sprauel@irt-saintexupery.com" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "tqdm",
    "pytrec_eval",
    "plotly",
    "pydantic",
    "pre-commit>=2.1.1",
    "farm-haystack==1.22.1",
    "sentence-transformers==2.2.2",
    "ragas",
    "unstructured[md]",
    "litellm"
]

[project.optional-dependencies]
all = [
    "forcolate",
    "sentence-transformers==2.2.2",
    "huggingface_hub",
    "datasets"
]
huggingface = [
    "huggingface_hub",
    "datasets",
    "ragas",
    "unstructured"
]

[tool.setuptools]
package-dir = {"" = "."}

[tool.setuptools.packages.find]
where = ["."]
include = ["ragformance*", "ragformance.*"]

[project.urls]
"Homepage" = "https://github.com/FOR-sight-ai/RAGFORmance"
"Bug Tracker" = "https://github.com/FOR-sight-ai/RAGFORmance/issues"

[project.scripts]
ragformance = "ragformance.End_to_end_runner.run:main"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0"
pytest-cov = "^4.0"

[tool.pytest.ini_options]
python_files = "test_*.py tests_*.py"
python_classes = "Test* Tests*"
python_functions = "test_* tests_*"
testpaths = [
    "tests",
]
