[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "organizations-local"
version = "0.0.23" # https://pypi.org/project/organizations-local
description = "organizations-local Python Package"
readme = "README.md"
authors = [
    "Circlez.ai <info@circlez.ai>",
]
