[project]
name = "FlowViewFt"
version = "0.1.3"
description = "FlowViewFt es una libreria para crear aplicaciones con Flet sinplificando las rutas y el manejo de estados."
readme = "README.md"
requires-python = ">=3.6"
authors = [
    { name = "HÃ©ctor", email = "danielramirezr27@gmail.com" }
]
license = { text = "MIT" }
keywords = ["testing", "logging", "example"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = [
    "flet[all]>=0.27.6",
    "repath>=0.1.2",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]